### ISSUE TITLE
import fail

### ISSUE THREAD

**Issue by KumaPlayWithShader** [ssitu/ComfyUI_UltimateSDUpscale#53]
from modules import processing, shared, images, devices, scripts
ImportError: cannot import name 'devices' from 'modules' (D:\ComfyUI_Portable\ComfyUI\custom_nodes\comfyui-reactor-node\modules\__init__.py)

**Comment by zeonagames** [comment]
I SOLVED, because There is no script file in there Download this scripts folder from there
https://github.com/Coyote-A/ultimate-upscale-for-automatic1111/tree/756bb50573ccc86ad2620b49f01f46d91a6fd682

and copy the scripts folder to custom_nodes\ComfyUI_UltimateSDUpscale\repositories\ultimate_sd_upscale\

Reset comfyui thats it

**Comment by dingshanliang** [comment]
> I SOLVED, because There is no script file in there Download this scripts folder from there https://github.com/Coyote-A/ultimate-upscale-for-automatic1111/tree/756bb50573ccc86ad2620b49f01f46d91a6fd682
> 
> and copy the scripts folder to custom_nodes\ComfyUI_UltimateSDUpscale\repositories\ultimate_sd_upscale\
> 
> Reset comfyui thats it

it doesn't work for me.

**Comment by ssitu** [comment]
> it doesn't work for me.

What version of reactor-node are you using?
